-- Schéma: přehled finančních výsledků bank — varianta pro PostgreSQL.
-- Liší se od schema/001_init.sql (SQLite) jen dialektem:
--   INTEGER PRIMARY KEY  -> GENERATED BY DEFAULT AS IDENTITY
--   TEXT timestamps      -> timestamptz
-- Datový model i sémantika jsou shodné. DROP na začátku = idempotentní build.

DROP TABLE IF EXISTS ingestion_run CASCADE;
DROP TABLE IF EXISTS fact CASCADE;
DROP TABLE IF EXISTS period CASCADE;
DROP TABLE IF EXISTS source CASCADE;
DROP TABLE IF EXISTS metric CASCADE;
DROP TABLE IF EXISTS bank CASCADE;

CREATE TABLE bank (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               TEXT UNIQUE NOT NULL,        -- 'cs', 'kb', 'csob', ...
    name               TEXT NOT NULL,
    parent_group       TEXT,                        -- 'Erste Group', ...
    country            TEXT DEFAULT 'CZ',
    reporting_currency TEXT DEFAULT 'CZK'
);

-- Kanonický katalog metrik (seed z config/metrics.yaml)
CREATE TABLE metric (
    code          TEXT PRIMARY KEY,
    label_cs      TEXT,
    label_en      TEXT,
    category      TEXT,
    unit          TEXT,
    type          TEXT,
    interim_basis TEXT,
    quarter_calc  TEXT,
    annual_calc   TEXT,
    annualize     INTEGER DEFAULT 0,
    formula       TEXT,
    headline      INTEGER DEFAULT 0
);

-- Provenance: odkud hodnota pochází
CREATE TABLE source (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id      INTEGER REFERENCES bank(id),
    doc_type     TEXT,
    file         TEXT,
    sheet        TEXT,
    retrieved_at timestamptz
);

-- Období: explicitně kvartál (Q) i rok (FY)
CREATE TABLE period (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id     INTEGER REFERENCES bank(id),
    fiscal_year INTEGER NOT NULL,
    period_type TEXT NOT NULL,                       -- 'Q' | 'FY'
    quarter     INTEGER,                             -- 1..4, NULL pro FY
    period_end  TEXT,
    UNIQUE(bank_id, fiscal_year, period_type, quarter)
);

-- Centrální "tidy" tabulka faktů: 1 řádek = (banka, metrika, období, báze)
CREATE TABLE fact (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id    INTEGER REFERENCES bank(id),
    code       TEXT REFERENCES metric(code),
    period_id  INTEGER REFERENCES period(id),
    basis      TEXT NOT NULL DEFAULT 'reported',     -- reported | adjusted
    value      DOUBLE PRECISION,
    value_ytd  DOUBLE PRECISION,
    source_id  INTEGER REFERENCES source(id),
    derived    INTEGER DEFAULT 0,
    UNIQUE(bank_id, code, period_id, basis)
);

CREATE TABLE ingestion_run (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at  timestamptz,
    finished_at timestamptz,
    status      TEXT,
    rows_loaded INTEGER,
    log         TEXT
);

CREATE INDEX idx_fact_lookup ON fact(bank_id, code, basis);
CREATE INDEX idx_period_lookup ON period(bank_id, fiscal_year, period_type);
